middyjs/middy

package-lock.json, package.json, src/middlewares/__tests__/jsonBodyParser.js, src/middlewares/__tests__/urlencodedBodyParser.js, src/middlewares/urlencodeBodyParser.js
=> Urlencoded body parser middleware

README.md, README.md.hb, docs/middlewares.md, src/middlewares/index.js
=> Added middleware docs

README.md, README.md.hb, docs/middlewares.md, package.json, src/middlewares/__tests__/s3KeyNormalizer.js, src/middlewares/index.js, src/middlewares/s3KeyNormalizer.js
=> Added first implementation of s3 key normalizer

.circleci/config.yml, README.md, README.md.hb, package-lock.json, package.json
See here the project: https://codecov.io/gh/Plnt9/middy
Closes: #28
=> Added integration with codecov

README.md, README.md.hb, package.json
=> Added gitter badge

package-lock.json, package.json
=> Update @types/aws-lambda to the latest version 🚀

package-lock.json, package.json
=> Updated jest to version 22

package-lock.json, package.json
=> Greenkeeper/@types/aws lambda 0.0.26

package-lock.json, package.json
=> Updated ajv deps

README.md, package-lock.json, package.json
=> Fix marked security warning on github

README.md, package-lock.json, package.json
=> Greenkeeper/jsdoc to markdown 4.0.1

.gitignore, README.md, docs/middlewares.md, package-lock.json, package.json, src/middlewares/__tests__/ssm.js, src/middlewares/index.js, src/middlewares/ssm.js
Originates from discussion in https://github.com/middyjs/middy/issues/90#issuecomment-358650963
Offtopic: I needed `invertObject` function and added the one from StackOverflow for now. What about adding `lodash`? The only concern, wouldn't it be too big for such a lightweight wrapper?
=> SSM Middleware

docs/middlewares.md, package-lock.json, package.json, src/middlewares/__tests__/cors.js, src/middlewares/cors.js
I really need this change now, so I took a part of https://github.com/middyjs/middy/pull/101
=> Set CORS headers in onError phase as well

package-lock.json, package.json
=> fix: include typescript definitions in NPM package

package-lock.json, package.json
This is now a current version in Lambda, see https://twitter.com/vladholubiev/status/974824935041519616
=> Update aws-sdk to 2.205.0

docs/middlewares.md, middlewares.d.ts, package-lock.json, package.json
Fixed wrong path import https://github.com/middyjs/middy/issues/136
fixes #136
=> Fixed wrong path import

middlewares.d.ts, package-lock.json, package.json
Quick pull request to add interface for the option available with httpPartialResponse middleware.
=> Add httpPartialResponse options interface

README.md, README.md.hb, docs/middlewares.md, package-lock.json, package.json
Hello,
I've written a few changes to the documentation (prompted by #148).
I've done the following:
- read through all of the documentation and made language changes to improve the readability
- rewritten the section on async to make it clearer
- done partial rewrites of the sections for ssm and warmup middlewares
Let me know if I've messed anything up (and thanks to @garyhollandxyz for checking over my work!)
=> Documentation changes

lerna.json, package-lock.json, package.json, packages/cache/package.json, packages/core/package.json, packages/do-not-wait-for-empty-event-loop/package.json, packages/http-content-negotiation/package.json, packages/http-cors/package.json, packages/http-error-handler/package.json, packages/http-event-normalizer/package.json, packages/http-header-normalizer/package.json, packages/http-json-body-parser/package.json, packages/http-partial-response/package.json, packages/http-urlencode-body-parser/package.json, packages/s3-key-normalizer/package.json, packages/ssm/README.md, packages/ssm/__tests__/index.js, packages/ssm/index.d.ts, packages/ssm/index.js, packages/ssm/package.json, packages/validator/package.json, packages/warmup/package.json
Thanks to @theburningmonk for these changes
=> Backport changes to ssm in 0.x by @theburningmonk

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, lerna.json, package.json, packages/cache/package.json, packages/core/package.json, packages/do-not-wait-for-empty-event-loop/package.json, packages/http-content-negotiation/package.json, packages/http-cors/package.json, packages/http-error-handler/package.json, packages/http-event-normalizer/package.json, packages/http-header-normalizer/package.json, packages/http-json-body-parser/package.json, packages/http-partial-response/package.json, packages/http-urlencode-body-parser/package.json, packages/s3-key-normalizer/package.json, packages/ssm/package.json, packages/validator/package.json, packages/warmup/package.json
Closes #127 
This is a first stab at it. Let me know what you think
=> Adds GitHub PR and Issue templates

lerna.json, package-lock.json, package.json, packages/cache/package.json, packages/core/package.json, packages/do-not-wait-for-empty-event-loop/package.json, packages/http-content-negotiation/package.json, packages/http-cors/package.json, packages/http-error-handler/package.json, packages/http-event-normalizer/package.json, packages/http-header-normalizer/package.json, packages/http-json-body-parser/package.json, packages/http-partial-response/package.json, packages/http-urlencode-body-parser/package.json, packages/input-output-logger/README.md, packages/input-output-logger/__tests__/index.js, packages/input-output-logger/index.d.ts, packages/input-output-logger/index.js, packages/input-output-logger/package.json, packages/input-output-logger/tsconfig.json, packages/s3-key-normalizer/package.json, packages/ssm/package.json, packages/validator/package.json, packages/warmup/package.json
As discussed in #174 this is an basic implementation of input-output middleware. Some of you mentioned the possibility also to log errors, but considering the error middleware flow, I wasn't sure that it was something doable.
Closes #174
=> Add input output logger middleware

docs/middlewares.md, package-lock.json, package.json, src/middlewares/__tests__/httpSecurityHeaders.js, src/middlewares/httpSecurityHeaders.js, src/middlewares/index.js
Sorry it took me so long to get around to this.
Closes: https://github.com/middyjs/middy/issues/187
=> httpSecurityHeaders

README.md, package-lock.json, package.json
Fixes #219 #177 
To: @lmammino @kevinrambaud
Does this help reduce the noise of people submitting the same suggested fix?
=> Fix: Document requirements for use with TypeScript

README.md, README.md.hb, docs/middlewares.md, middlewares.d.ts, package-lock.json, package.json
=> Add secretsManager middleware TypeScript definition + README fixes

package-lock.json, package.json
=> chore: update husky to version 1.1.0, migration hooks

docs/middlewares.md, package-lock.json, package.json, src/middlewares/__tests__/functionShield.js, src/middlewares/functionShield.js, src/middlewares/index.js
We would like to contribute FunctionShield middleware - a very easy way to harden AWS Lambda execution environment.
https://www.jeremydaly.com/serverless-security-with-functionshield/
https://www.puresec.io/function-shield
=> Added FunctionShield middleware

README.md.hb
First contribution 🎉
This fixes #260.
=> docs: fix broken link

package-lock.json, package.json
=> Update FunctionShield to 1.2.2

README.md, README.md.hb, package-lock.json, package.json
Hey folks,
I improved the documentation about how define required json properties on event.
Hope it helps!
=> add: required properties list

middlewares.d.ts, package-lock.json, package.json, src/middlewares/__tests__/jsonBodyParser.js, src/middlewares/jsonBodyParser.js
This PR introduces a [`reviver`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse#Parameters) option for `http-json-body-parser` to pass through to `JSON.parse`.  
From [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse):
> An optional reviver function can be provided to perform a transformation on the resulting object before it is returned.
A `1.0-alpha` PR is also available in #331
=> Support reviver parameter in for http-json-body-parser

lerna.json, package.json, packages/cache/package.json, packages/core/package.json, packages/do-not-wait-for-empty-event-loop/package.json, packages/error-logger/package.json, packages/function-shield/package.json, packages/http-content-negotiation/package.json, packages/http-cors/package.json, packages/http-error-handler/package.json, packages/http-event-normalizer/package.json, packages/http-header-normalizer/package.json, packages/http-json-body-parser/package.json, packages/http-partial-response/package.json, packages/http-response-serializer/package.json, packages/http-security-header/package.json, packages/http-urlencode-body-parser/package.json, packages/input-output-logger/package.json, packages/s3-key-normalizer/package.json, packages/secrets-manager/package.json, packages/ssm/package.json, packages/validator/package.json, packages/warmup/README.md, packages/warmup/__tests__/index.js, packages/warmup/index.d.ts, packages/warmup/index.js, packages/warmup/package.json
Ports #345 by @lbertenasco to `v1.0.0-alpha`
=> Port waitForEmptyEventLoop in Warmup middlware (#345) to v.1.0.0 branch

README.md, README.md.hb, package-lock.json, package.json
Adding [middy-env](https://www.npmjs.com/package/middy-env) to 3rd party middleware list
=> Add middy-env to 3rd party middleware list

lerna.json, package-lock.json, package.json, packages/cache/package.json, packages/core/package.json, packages/do-not-wait-for-empty-event-loop/__tests__/index.js, packages/do-not-wait-for-empty-event-loop/index.js, packages/do-not-wait-for-empty-event-loop/package.json, packages/error-logger/package.json, packages/function-shield/package.json, packages/http-content-negotiation/package.json, packages/http-cors/package.json, packages/http-error-handler/package.json, packages/http-event-normalizer/package.json, packages/http-header-normalizer/package.json, packages/http-json-body-parser/package.json, packages/http-partial-response/package.json, packages/http-response-serializer/package.json, packages/http-security-header/package.json, packages/http-urlencode-body-parser/package.json, packages/input-output-logger/package.json, packages/s3-key-normalizer/package.json, packages/secrets-manager/package.json, packages/ssm/__tests__/index.js, packages/ssm/package.json, packages/validator/package.json, packages/warmup/package.json, wallaby.config.js
=> Propagate thrown error when "runOnError" is true in doNotWaitForEmptyEventLoop

index.d.ts, package-lock.json, package.json
Closes #398
Updates `HandlerLambda` types
=> Update types to reflect `aws lambda` types.

.circleci/config.yml, lerna.json, package-lock.json, package.json, packages/cache/package.json, packages/core/package.json, packages/db-manager/package.json, packages/do-not-wait-for-empty-event-loop/package.json, packages/error-logger/package.json, packages/function-shield/package.json, packages/http-content-negotiation/package.json, packages/http-cors/package.json, packages/http-error-handler/package.json, packages/http-event-normalizer/package.json, packages/http-header-normalizer/package.json, packages/http-json-body-parser/package.json, packages/http-partial-response/package.json, packages/http-response-serializer/package.json, packages/http-security-headers/package.json, packages/http-urlencode-body-parser/package.json, packages/http-urlencode-path-parser/package-lock.json, packages/http-urlencode-path-parser/package.json, packages/input-output-logger/package.json, packages/s3-key-normalizer/package.json, packages/secrets-manager/package.json, packages/ssm/package.json, packages/validator/package.json, packages/warmup/package.json
Closes: https://github.com/middyjs/middy/issues/355
FYI I'm working on middy stuff all week. Will be on Gitter as well.
=> ci: deprecate old runtimes

README.md
=> Add middy-mongoose-connector 3rd-party middleware

README.md
It adds a new community middleware to the README.md file.
No
N/A
N/A
N/A
Todo list
---------
=> docs: added a community middleware

README.md
This will fix README link for https://github.com/middyjs/middy/#more-details-on-creating-middlewares
Yes - https://github.com/middyjs/middy/issues/534
…
**AWS SDK …
=> fix documentation - README link 

README.md
Hello Middy team,
I've been using Middy for a while and it saved me a lot of time so thank you for your effort!
Since I needed a middleware to manage roles permission using Amazon Cognito user groups I decided to spend some more time to give a little contribution to the community so here we are.
I added a new community generated middleware on the README. Since Amazon Cognito user pools enables you to create and manage groups, add users to groups, and remove users from groups I developed a middleware that checks for the user’s groups permission and authorizes user requests.
Todo list
---------
[x] …
=> Added a new community generated middleware

packages/secrets-manager/README.md
see https://github.com/middyjs/middy/blob/040ad16d0cbb8c41225a609fa8aeccd2a20d9436/packages/secrets-manager/index.js#L60-L63
=> docs(secrets-manager): fix Options

packages/http-error-handler/README.md
=> Document order with http-response-serializer

packages/secrets-manager/README.md
Mention in documentation that you can also use secret ARN
No
No
No
References:
https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_GetSecretValue.html
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SecretsManager.html#getSecretValue-property
=> Mention in docs that you can also use ARN

packages/http-multipart-body-parser/index.d.ts
=> #573 Fix busboy options property key

packages/cloudwatch-metrics/README.md, packages/cloudwatch-metrics/__tests__/index.js, packages/cloudwatch-metrics/index.d.ts, packages/cloudwatch-metrics/index.js, packages/cloudwatch-metrics/package-lock.json, packages/cloudwatch-metrics/package.json
Implements #618 
**Node.js Versions:** 12
**Middy Versions:** 2.0.0-alpha6
**AWS SDK Versions:** No relevant
Todo list
---------
[ x ] Feature/Fix fully implemented
[ x ] Added tests
[ x ] Updated relevant documentation
[ x ] Updated relevant examples
=> Add metrics middleware

docs/README.md
Typos:
retunr => return
provess => process
…
…
Todo list
---------
[ ] Updated relevant …
=> Fix minor README.md typos

packages/input-output-logger/README.md
Typo in the README title
No
No
No
It wasn't tested
Todo list
---------
[x] Updated relevant examples
=> Typo in README

README.md
Wording change in the documentation
No
=> Variable name changed to match example function

README.md
Update the list of community generated middleware with to list of [middy-recaptcha](https://www.npmjs.com/package/middy-recaptcha)
No
I'll expand the documentation further with a write-up soon.
**Node.js Versions:** > Node 12.x
**Middy Versions:** 2.0
**AWS SDK Versions:** 2.x
=> chore: added middy-recaptcha

packages/rds-signer/index.js, packages/secrets-manager/index.js, packages/ssm/README.md, packages/ssm/__tests__/index.js, packages/ssm/index.js, packages/sts/index.js, packages/util/__tests__/index.js, packages/util/index.js
=> Force cache clean when aws service throws error

README.md
middy-idempotent
Only adds another community generated middleware
No
**Node.js Versions:**
12.x, 14.x
**Middy Versions:**
2.0
Todo list
---------
=> chore(docs): adding community generated middleware

README.md
Documentation fix
No
No
No
No
Todo list
---------
=> Fix syntax mistake

packages/input-output-logger/README.md, packages/input-output-logger/__tests__/index.js, packages/input-output-logger/index.js
=> Add in ability to log aws context

packages/input-output-logger/README.md
=> Adjusted title in README.md

README.md
Correcting spelling in the main README.md
[X] Updated relevant documentation
=> Typo: Updating README.md

packages/http-multipart-body-parser/README.md
Corrects documentation
[X] Updated relevant documentation
[X] Updated relevant examples
=> Updating import in README

README.md
…
…
…
Todo list
---------
[ ] Updated relevant …
=> Add `middy-event-loop-tracer`, `middy-console-logger` and `middy-invocation` plugins into README

docs/UPGRADE.md, packages/s3-object-response/README.md, packages/s3-object-response/index.js, packages/ws-response/README.md, packages/ws-response/__benchmarks__/index.js, packages/ws-response/__tests__/index.js, packages/ws-response/index.d.ts, packages/ws-response/index.js, packages/ws-response/index.test-d.ts, packages/ws-response/package-lock.json, packages/ws-response/package.json
new middleware #602
cc @KillDozerX2
=> New Middleware: WebSocket Response

docs/UPGRADE.md, packages/service-discovery/README.md, packages/service-discovery/__tests__/index.js, packages/service-discovery/index.d.ts, packages/service-discovery/index.js, packages/service-discovery/index.test-d.ts, packages/service-discovery/package-lock.json, packages/service-discovery/package.json
New middleware #747
cc @dennisc9 @sahilhaslani
=> New Middleware: Service Discovery

packages/input-output-logger/__tests__/index.js, packages/input-output-logger/index.js, packages/input-output-logger/invalid-logger.exception.js
This PR provides a more specific error message when an invalid logger is provided to the input-out middleware.
Yes, #799.
**TODO:**
[] Feature/Fix fully implemented
[] Resolve import issues
[x] Updated relevant examples
=> refactor(packages/input output): adjust invalid logger exception

docs/UPGRADE.md, packages/ws-json-body-parser/README.md, packages/ws-json-body-parser/__benchmarks__/index.js, packages/ws-json-body-parser/__tests__/index.js, packages/ws-json-body-parser/index.d.ts, packages/ws-json-body-parser/index.js, packages/ws-json-body-parser/index.test-d.ts, packages/ws-json-body-parser/package-lock.json, packages/ws-json-body-parser/package.json, packages/ws-router/README.md, packages/ws-router/__benchmarks__/index.js, packages/ws-router/__tests__/index.js, packages/ws-router/index.d.ts, packages/ws-router/index.js, packages/ws-router/index.test-d.ts, packages/ws-router/package-lock.json, packages/ws-router/package.json
Yeah, for completeness.
Which do you prefer? `ws-json-body-parser` or `ws-normalizer`?
=> New WebSocket Middlewares

docs/UPGRADE.md, packages/validator/README.md, packages/validator/__tests__/index.js, packages/validator/index.d.ts, packages/validator/index.js, packages/validator/index.test-d.ts, packages/validator/package-lock.json, packages/validator/package.json
=> Add in context validation

packages/http-router/index.d.ts, packages/http-router/index.test-d.ts, packages/http-router/package-lock.json, packages/http-router/package.json
Adds typings  & tests to `packages/http-router`.
Continuation of #838.
=> feat(packages/http-router): adding typings and tests

packages/ws-router/index.d.ts, packages/ws-router/index.test-d.ts, packages/ws-router/package-lock.json, packages/ws-router/package.json
Types added in the ws-router package
=> feat: improve ws-router types

website/docs/routers/ws-router.md
Fix the ws-router's documentation
=> docs: fix ws-router documentation

packages/cloudwatch-metrics/README.md, website/docs/middlewares/cloudwatch-metrics.md, website/docs/middlewares/http-partial-response.md
- Add filteringKeyName options into http-partial-response
- Fix namespace typo
=> docs: improvement

packages/s3-object-response/index.d.ts
Improve s3 object response options
=> feat: improve s3 object response options

packages/http-multipart-body-parser/index.js
@willfarrell also quickly tested in my project, works :v:
fixes #864
=> fix filename and mimetype

website/docs/events/api-gateway-rest.md
Fix typo in httpResponseSerializerMiddleware docs
=> fix typo in httpResponseSerializerMiddleware docs

packages/http-error-handler/__tests__/index.js, packages/http-error-handler/index.js
=> Feature: http-error-handler to support error headers

packages/http-router/index.d.ts
Fixes #895 
I honestly don't think my idea is good enough as a solution, but any progress is progress.
It should be remade when someone has a better idea.
=> feat(http-router): Support V2 types

packages/http-router/index.d.ts
=> feat(http-router): Update Typescript Types

packages/http-json-body-parser/index.d.ts, website/docs/middlewares/http-json-body-parser.md
In favor of https://github.com/middyjs/middy/pull/973#issuecomment-1362549021
Let me also delete its document.
=> fix(http-json-body-parser): delete rawBody from Event type

packages/http-json-body-parser/__tests__/index.js, packages/http-json-body-parser/index.d.ts, packages/http-json-body-parser/index.js, packages/http-multipart-body-parser/__tests__/index.js, packages/http-multipart-body-parser/index.d.ts, packages/http-multipart-body-parser/index.js, packages/http-urlencode-body-parser/__tests__/index.js, packages/http-urlencode-body-parser/index.d.ts, packages/http-urlencode-body-parser/index.js, website/docs/middlewares/http-json-body-parser.md, website/docs/middlewares/http-multipart-body-parser.md, website/docs/middlewares/http-urlencode-body-parser.md
=> Add `disableContentTypeError` to body parse middlewares

packages/dynamodb/README.md, packages/dynamodb/__benchmarks__/index.js, packages/dynamodb/__tests__/index.js, packages/dynamodb/index.d.ts, packages/dynamodb/index.js, packages/dynamodb/index.test-d.ts, packages/dynamodb/package-lock.json, packages/dynamodb/package.json, website/docs/events/01-intro.md, website/docs/middlewares/dynamodb.md
=> New Middleware:`dynamodb` - pull configs from DynamoDB

.github/workflows/release.yml, .github/workflows/tests.yml
=> CommonJS undefined "default" in cloudwatch-metrics middleware

packages/http-router/index.d.ts, packages/http-router/index.js
=> Feature: Added "HEAD" to Method object in "http-router" package

website/docs/middlewares/validator.md
The validator example i wish i had 😄
=> docs: validator event body example

packages/http-router/index.d.ts, packages/http-router/index.test-d.ts
=> feat: update http-router Method to inline allowed values

packages/core/index.d.ts, packages/core/index.test-d.ts
=> fix(packages/core): resolve type error when using plugin params on middy fn

packages/validator/__benchmarks__/index.js
- small thing I noticed while working on #1104 , the benchmark wasn't testing a compiled schema getting passed in
=> fix: validator benchmark

website/docs/integrations/lambda-powertools.md
This PR introduces a new section to the documentation page dedicated to Powertools. This new section uses the same format & structure as the existing ones but describes the [Idempotency utility](https://docs.powertools.aws.dev/lambda/typescript/latest/utilities/idempotency/), which was released some time after the last edit of the page.
Additionally, the PR also fixes #1114 by correcting the example for the Logger and using the correct construct parameter (`serviceName` instead of `service`).
=> docs: add Powertools idempotency + fix typo

.github/workflows/website-publish.yml, website/docs/routers/http-router.md, website/docs/routers/ws-router.md
- use node 20
- updates checkout and setup-node actions
=> chore(website): Update website-publish.yml

packages/util/index.d.ts, packages/util/type-utils.test-d.ts, packages/validator/transpile.test-d.ts
=> Set explicit import type

packages/core/__tests__/index.js, packages/core/index.js
=> fix: middyjs#1189 write prelude in streamifyResponse with string body

website/docs/integrations/lambda-powertools.md
Hi,
Middy looks like super cool, I can't wait to try it. 
Meanwhile I discovered an import that can be updated in the logging module. 
Let me know if it works for you too.
All the best
=> Update aws-lambda-powertools imports

packages/http-router/index.d.ts, packages/http-router/index.test-d.ts
resolves https://github.com/middyjs/middy/issues/1175#issuecomment-1945658104
=> fix(packages/http-router): refine return type to include event and response

packages/core/index.d.ts, packages/core/index.test-d.ts
=> revert(core): rollback input handler plain lambda handler support

website/docs/intro/06-typescript.md
Some minor documentation fixes to get the example working.
=> :memo: TypeScript documentation fixes

packages/http-cors/__tests__/index.js, packages/http-cors/index.js
=> http-cors: Fix var base response headers

lint-staged.config.js, package-lock.json, package.json, packages/core/index.d.ts, packages/core/index.test-d.ts
This PR adds TypeScript type definitions for the `Request.earlyResponse` field. Fixes issue https://github.com/middyjs/middy/issues/1275
=> fix: add TypeScript type definition for request.earlyResponse

packages/http-json-body-parser/__tests__/index.js, packages/http-json-body-parser/index.js
=> fix(http-json-body-parser): allow "undefined" body if disableContentTypeError:true

website/docs/middlewares/third-party.md
Add `middy-mcp` in listed third-party middlewares
=> Add middy-mcp third party middleware

website/docs/middlewares/sqs-partial-batch-failure.md
---
name: Pull request
about: Pull request
title: ''
labels: ''
assignees: ''
---
The link referring to ReportBatchItemFailures was broken and not redirecting to the correct page, examples also seemed unclear and insufficient without looking at the AWS documentation.
Updated the link to go to the correct documentation, and took examples from there as examples on how to use the middleware.
**Does this close any currently open issues?**
No.
**Any relevant logs, error output, etc?**
No.
**Environment:**
n/a
**Any other comments?**
No
**Todo List:**
=> Updated a broken link and examples in documentation for sqs-partial-batch-failure

packages/input-output-logger/index.js, packages/input-output-logger/index.test.js
---
name: Pull request
about: Pull request
title: 'Fix input-output-logger to log webstream responses'
labels: ''
assignees: ''
---
Handles logging of webstream responses
**Does this close any currently open issues?**
#1330 
**Environment:**
- Node.js: [22]
- Middy: [6.2.4]
- AWS SDK [2.1692.0]
=> fix: log web stream responses

website/docs/intro/08-history.md
---
name: Pull request
about: Pull request
title: 'docs: fix 6.0.0 release date'
labels: ''
assignees: ''
---
The current history page has the 6.0.0 release date set to "2024-11-??". Based on the GitHub releases page, 6.0.0 was created on 2024-11-23. The date has been fixed to reflect the releases page.
**Does this close any currently open issues?**
N/A
**Any relevant logs, error output, etc?**
N/A
**Environment:**
N/A
**Any other comments?**
N/A
**Todo List:**
=> docs: fix 6.0.0 release date
