docs/middlewares.md, package.json
Middlewares documentation is missing a link to `doNotWaitForEmptyEventLoop` middleware
=> docs/missing link to doNotWaitForEmptyEventLoop middleware

.gitignore, package-lock.json, package.json, typescript/middy.d.ts
I found an issue using the default export on the typescript types, so I refactor the types to create a signature of the middy default function and add a Namespace with the same name to the rest of the types, so you can use the following imports:
```typescript
import * as middy from 'middy';
import {IMiddy} from 'middy';
```
=> Fix root export on typings and update AWS lambda types

README.md, README.md.hb, package-lock.json, package.json, src/__tests__/middy.js, src/middy.js, typescript/middy.d.ts
Closes #52 
TODO:
**READY FOR REVIEW** 🤓
=> Added support for async await in handler

package-lock.json, package.json, src/middlewares/__tests__/urlencodeBodyParser.js, src/middlewares/urlEncodeBodyParser.js
Decode body when Content-Type contains more than 'application/x-www-form-urlencoded'.
Example: 'application/x-www-form-urlencoded; charset=UTF-8'
In current state urlEncodeBodyParser & validator middleware are useless if the origin is not exactly sending 'application/x-www-form-urlencoded'.
In my case I don't control the origin request unfortunately!
=> Fix urlEncodeBodyParser when Content-Type header contains charset

README.md, README.md.hb, docs/middlewares.md, package-lock.json, package.json, src/middlewares/__tests__/httpHeaderNormalizer.js, src/middlewares/httpHeaderNormalizer.js, src/middlewares/index.js
=> HTTP Header Normalizer Middleware

README.md, README.md.hb, docs/middlewares.md, package-lock.json, package.json, src/middlewares/__tests__/httpContentNegotiation.js, src/middlewares/httpContentNegotiation.js, src/middlewares/index.js
This PR implements a middleware that will simplify [HTTP content negotiation](https://tools.ietf.org/html/rfc7231#section-5.3) parsing and easily allow an API gateway Lambda function to support multiple charsets, encoding (e.g. compression algorithms), languages or content-types.
My current approach is to use the module [negotiator](http://npm.im/negotiator) (used also by express and koa) to parse the content negotiation headers and expand the current event with data that can be reused by other middlewares or in the handler.
For instance, this middleware can parse the incoming `Accept` header and expose the resulting information in something like `event.preferredMediaType`.
A usage example might look like the following:
```javascript
const middy = require('middy')
const { …
```
=> Middleware HTTP Content Negotiation

docs/middlewares.md, package-lock.json, package.json, src/middlewares/__tests__/ssm.js, src/middlewares/ssm.js, wallaby.config.js
Can't believe I forgot this in the initial implementation
=> Add caching to the SSM middleware

package-lock.json, package.json, typescript/middy.d.ts
Hi! I was writing some tests for my App and I noticed this:
(newTechHandler is a handler returned by middy())
this PR fixes this problem
=> Make IMiddy extend Handler

docs/middlewares.md, middlewares.d.ts, package-lock.json, package.json, src/middlewares/__tests__/cors.js, src/middlewares/cors.js
Adds the ability to set Access-Control-Allow-Credentials and Access-Control-Allow-Headers for the CORS middleware.
It solves 2 of the 4 options from #43
=> Extra CORS options

docs/middlewares.md, package-lock.json, package.json
Fix references to middlewares at httpHeaderNormalizer and validator middleware documentation
=> Documentation: Fix references to middlewares 

package-lock.json, package.json
Included the new middleware.d.ts type definition file in the package.json files array.
=> Include middleware type definition when creating releases

README.md, README.md.hb, middlewares.d.ts, package-lock.json, package.json
Adds ssm middleware to main README document, with link to middleware docs. Closes #140.
Also capitalises the middleware descriptions in the main README where it had been missed, so it's all consistent now.
=> Add SSM middleware to main README document

README.md, docs/middlewares.md, middlewares.d.ts, package-lock.json, package.json, src/middlewares/__tests__/httpErrorHandler.js, src/middlewares/httpErrorHandler.js, tsconfig.json
This implements a `logger` option in the `httpErrorHandler` middleware as discussed in #155
This also changes the way the exception is checked to avoid issues with environments in which multiple versions of `http-errors` are installed (see [comment](https://github.com/middyjs/middy/pull/156#discussion_r182543535)).
CC: @thomasedwards
=> Added logger option in httpErrorHandler middleware

README.md, README.md.hb, docs/middlewares.md, package-lock.json, package.json, src/middlewares/__tests__/ssm.js, src/middlewares/ssm.js
Introduces functionality discussed in #142. I thought a working example might help!
With this version of the ssm middleware, you can specify both a `names` object and a `paths` object in `config`. (I.e. a map of `LOCAL_NAME -> PARAMETER_NAME` and `LOCAL_NAME -> PARAMETER_PATH` respectively.
This is currently closer to @lmammino's suggested approach.
=> Update ssm middleware to accept paths

README.md, docs/middlewares.md, package-lock.json, package.json, src/middlewares/__tests__/validator.js, src/middlewares/validator.js
Includes: ajv i18n support (Default: `en`)
=> feat: add in i18n support for validator

middlewares.d.ts, package-lock.json, package.json
Hey there,
Currently when I build a project using middy I get the following reported back from `tsc`:
```
$ tsc -p .
node_modules/middy/middlewares.d.ts(4,19): error TS7016: Could not find a declaration file for module './src/middy'. '/Users/ossareh/dev/src/code.famfi.co/mono/famfi.co/mailchimp/node_modules/middy/src/middy.js' implicitly has an 'any' type.
Try `npm install @types/middy` if it exists or add a new declaration (.d.ts) file containing `declare module 'middy';`
```
This patch fixes this issue:
- middleware.d.ts references middy using the relative reference `./src/middy`;
- this bypasses the types defined in `index.d.ts`; and thus causes the issue
=> Refer to root module to correctly bring in types

package-lock.json, package.json, src/middlewares/__tests__/ssm.js, src/middlewares/ssm.js
Hello,
I found out today (the hard way) that [SSM.getParametersByPath](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SSM.html#getParametersByPath-property) only returns up to 10 parameters per call.
It has a MaxResults property but you can't set this to higher than 10.
Therefore I've refactored the middleware to work recursively if there's a NextToken in the response (indicating that there are additional results).
Let me know if you foresee any issues or need me to change anything.
Thanks in advance.
=> Refactor SSM getParametersByPath to work recursively

lerna.json, package-lock.json, package.json, packages/cache/package.json, packages/core/package.json, packages/cors/__tests__/index.js, packages/cors/index.js, packages/cors/package.json, packages/do-not-wait-for-empty-event-loop/package.json, packages/http-content-negotiation/__tests__/index.js, packages/http-content-negotiation/index.js, packages/http-content-negotiation/package.json, packages/http-error-handler/package.json, packages/http-event-normalizer/package.json, packages/http-header-normalizer/README.md, packages/http-header-normalizer/__tests__/index.js, packages/http-header-normalizer/index.d.ts, packages/http-header-normalizer/index.js, packages/http-header-normalizer/package.json, packages/http-json-body-parser/__tests__/index.js, packages/http-json-body-parser/index.js, packages/http-json-body-parser/package.json, packages/http-partial-response/package.json, packages/http-urlencode-body-parser/__tests__/index.js, packages/http-urlencode-body-parser/index.js, packages/http-urlencode-body-parser/package.json, packages/s3-key-normalizer/package.json, packages/ssm/package.json, packages/validator/package.json, packages/warmup/package.json
Modified the middleware "http-header-normalizer" to normalise to lowercase. There is an extra options now in the middleware, so you can decide to normalise to camelCase.
Modified the other middleware:
- cors
- http-content-negotiation
- http-json-body-parser
- http-urlencode-body-parser
to handle headers in lowercase or camel case.
I didn't updated the documentation of the middlewares about the handling of both format of header, but I don't think it's necessary.
Closes #166
=> Http header normaliser to lowercase

docs/middlewares.md, middlewares.d.ts, package-lock.json, package.json, src/middlewares/__tests__/ssm.js, src/middlewares/ssm.js
- support cache invalidation for the SSM middleware
- refactored the corresponding tests a bit to make it easier to run scenarios that involves multiple invocations
=> add SSM cache invalidation

docs/middlewares.md, package-lock.json, package.json, src/middlewares/__tests__/cors.js, src/middlewares/cors.js
Changes the cors middleware options to accept an array of origins. If the request origin matches an origin in the options it is returned. Otherwise the first origin is returned.
=> Allow cors middleware to specify multiple allowed origins

.circleci/config.yml, package-lock.json, package.json
These changes enable building middy against node v6 (current) and node v8 (next). Additionally it leverages the work flow feature of CircleCI to ensure deploys only happen if the code base passes tests on *both* node versions.
This was discussed in #182 with @vladgolubev and @lmammino 
As with the original file we only trigger the deploy job if we're on master; we just utilize the circleci config to control this instead of using a shell script to check the branch name.
I chose not to run coverage for the `build_next` job as the underlying node version shouldn't make a difference to the output here. Also we only take the workspace from v6 and deploy that since nothing in the build vary's based on node version this should be just fine.
=> Node8 build

index.d.ts, middlewares.d.ts, package-lock.json, package.json, src/__tests__/middy.types.ts, src/middlewares/__tests__/cors.types.ts, tsconfig.json
As per #182 this fixes the types issues on IMiddy and ICorsOptions. `before`, `after`, and `onError` on IMiddy were incorrectly configured:
- they did not take a function
- they did not return themselves
While `ICorsOptions` itself was optional when `cors()` was being called, the individual properties of it were not.
The project already had the infrastructure to run tests but was missing a few things:
- `@types/node` were not present, so `typings-tester` would fail
- it was easy to miss this because `test:typings` was not part of the build workflow; I've now added it to `npm test`.
I have examples of the tests failing:
- [tests against incorrect IMiddy](https://circleci.com/gh/ossareh/middy/37)
- [tests against incorrect ICorsOptions](https://circleci.com/gh/ossareh/middy/36)
These have …
=> Fix IMiddy and ICorsOptions type definitions

middlewares.d.ts, package-lock.json, package.json, src/middlewares/__tests__/cors.types.ts
Fixes #204 as well as defining ICorsOptions.origins which was introduced with #194 but not included in #200 for some reason; I must have branched before that landed and didn't update.
I've verified the test fix, if I run the tests without the changes to middlewares.d.ts I get:
```
$npm run test:typings
> middy@0.15.6 test:typings /Users/ossareh/dev/src/github.com/ossareh/middy
> typings-tester --config tsconfig.json index.d.ts middlewares.d.ts src/__tests__/*.types.ts src/**/__tests__/*types.ts
Semantic: src/middlewares/__tests__/cors.types.ts (21, 9) Argument of type '{ origins: string[]; }' is not assignable to parameter of type 'ICorsOptions | undefined'.
Object literal may only specify known properties, and 'origins' does not exist in type 'ICorsOptions | undefined'.
```
=> fix: ICorsOptions now has origins option

.gitignore, package-lock.json, package.json, src/__tests__/middy.js, src/middy.js
Thanks for your effort on this package, it's helped me refactor a lot of async setup code into middlewares 👍.
By passing a callback to the handler *and* waiting for a returned
promise to resolve, onHandlerSuccess and onHandlerError can be called
twice. Wrapping them with `once` fixes this.
PS Installing `once` has rewritten a bunch of `package-lock.json`, which I'm guessing is because NPM is using a new format in more recent versions; I'm using 6.1.0.
=> Fix a bug where handler callback is called more than once

package-lock.json, package.json, src/middlewares/__tests__/ssm.js, src/middlewares/ssm.js
**Summary**
In the `ssm` middleware, when the `cache` option is enabled we skip the call to SSM but it also skips the step to set the params onto the context.
This wasn't caught in the tests as the tests didn't verify that the properties are set on the invocation context.
**Changes**
- fixed some ssm plugin tests which weren't validating that values are set in the context
- changed places where mockReset is used where it  should be mockClear (since we just want to reset the invocation count)
- cache the SSM response, and apply the cached params even when skip calling SSM
=> bugfix - ssm middleware - setToContext doesn't work when cache option is enabled

README.md, README.md.hb, docs/middlewares.md, src/middlewares/__tests__/secretsManager.js, src/middlewares/secretsManager.js
Hello,
It seemed to me that checking if each secret is available at start of lambda function is a bit too much if you are in situation where missing secrets mean there is no point for lambda to run.
=> Fail lambda if shouldFail flag provided

README.md, lerna.json, package-lock.json, package.json, packages/cache/package.json, packages/core/package.json, packages/do-not-wait-for-empty-event-loop/package.json, packages/error-logger/package.json, packages/http-content-negotiation/package.json, packages/http-cors/package.json, packages/http-error-handler/package.json, packages/http-event-normalizer/package.json, packages/http-header-normalizer/package.json, packages/http-json-body-parser/package.json, packages/http-partial-response/package.json, packages/http-security-headers/package.json, packages/http-urlencode-body-parser/package.json, packages/input-output-logger/package.json, packages/s3-key-normalizer/package.json, packages/secrets-manager/README.md, packages/secrets-manager/__tests__/index.js, packages/secrets-manager/index.d.ts, packages/secrets-manager/index.js, packages/secrets-manager/package.json, packages/ssm/package.json, packages/validator/package.json, packages/warmup/package.json
1.0.0 doesn't seem to work on node v6.10 because of the issue reported here: https://github.com/jsdom/jsdom/issues/2304, at least for me.
I'd say it's not a regression from this pull request so I parked it for now.
Works like a charm on 8.10.0 though.
When it comes to #235, looks like @theburningmonk took care of it already so I just updated typings
Edit: CI passed for Node 6.10, maybe it's because of cache?
=> update secrets manager with throwOnFailedCall flag

docs/middlewares.md, package-lock.json, package.json, src/middlewares/jsonBodyParser.js
Just got bit by this because I didn't also have the `.use(httpHeaderNormalizer())` right above `.use(jsonBodyParser())`
This will streamline the amount of middleware needed for JSON based APIs.
```
// this looked fine but was broken due to lowercase 'content-type' in my request.
exports.handler = middy(businessLogic)
.use(jsonBodyParser())
.use(validator({ inputSchema: schema.input }))
.use(httpErrorHandler())
```
```
// using httpHeaderNormalizer before fixed it but it's doing alot more than I need.
exports.handler = middy(businessLogic)
.use(httpHeaderNormalizer())
.use(jsonBodyParser())
.use(validator({ inputSchema: schema.input }))
.use(httpErrorHandler())
```
I think `jsonBodyParser` should normalize it's own `content-type` header =)
What do you think?
=> Support normalized 'content-type' for jsonBodyParser()

.circleci/config.yml, package-lock.json, package.json, src/middlewares/__tests__/ssm.js, src/middlewares/ssm.js
Hello,
In this PR I'd like to add functionality to automatically trigger handler when ssm parameter is regenerated - we use this data in other parts of code and need to be able to regenerate if any parameter changed.
While at it, I saw multiple vulnerabilities doing npm audit so I thought it would be sensible to make it a part of pipeline so nothing slips to production anymore (added only to Node8.10 as 6.10 doesn't have that command yet) .
Actually, npm audit is not available in Circle CI, had to revert this change
Cheers
=> Add onChange handler to ssm + audit packages

package-lock.json, package.json, src/middlewares/__tests__/s3KeyNormalizer.js, src/middlewares/s3KeyNormalizer.js
The s3KeyNormalizer middleware was not running because the version check was failing. AWS have updated S3 events and are now using a new version of 2.1. This PR updates the version number to run the normalizer when the version is 2.1. [AWS docs for S3 events](https://docs.aws.amazon.com/AmazonS3/latest/dev/notification-content-structure.html)
=> Updates S3 event version to allow event versions of 2.x

package-lock.json, package.json, src/middlewares/__tests__/httpEventNormalizer.js, src/middlewares/__tests__/httpHeaderNormalizer.js, src/middlewares/httpEventNormalizer.js, src/middlewares/httpHeaderNormalizer.js
Updated httpEventNormalizer and httpHeaderNormalizer to support multiValueHeaders/QueryStringParameters. Also updated appropriate tests
Reference: https://aws.amazon.com/blogs/compute/support-for-multi-value-parameters-in-amazon-api-gateway/
=> Support multiValueHeaders and multiValueQueryStringParameters - fix #251

index.d.ts, middlewares.d.ts, package-lock.json, package.json, src/__tests__/middy.types.ts
As per #275, it's a breaking change for people using Typescript, but it's as safe as it gets. the usage is 
```ts
import { APIGatewayProxyHandler, Context } from 'aws-lambda'
interface CustomContext extends Context {
haha?: boolean // needs ? because doesn't exist in original context when TS tries to infer the type
}
const get = middy<APIGatewayProxyHandler>( async (event, context: CustomContext) => {
return {
statusCode: 200,
body: ''
}
}).use(cors()).after((s, next) => { s.context; next() })
```
since it's a breaking change (for the types only), renamed the interfaces to force people rewrite it
custom data on "event" would then be:
```ts
import { Handler, APIGatewayProxyEvent, Context } from 'aws-lambda'
middy<Handler<APIGatewayProxyEvent & { extra: string, field: string }, {}>>( async …
```
=> Typescript typesafe, guards and generics

packages/secrets-manager/index.d.ts, packages/ssm/index.d.ts
This seems to be an oversight - the other middlewares have it, and ssm not having it breaks TypeScript imports
=> Add default export to ssm middleware

middlewares.d.ts, package-lock.json, package.json
I noticed the types for **httpSecurityHeaders** is added in 1.0.0-alpha but not master, so just do it to make it work for now.
=> Add types for httpSecurityHeaders

docs/middlewares.md, src/middlewares/__tests__/cors.js, src/middlewares/cors.js, src/middlewares/httpErrorHandler.js
Fixes #264 
Stumbled upon an issue this morning where we found that by using the `cors` middleware with `onError`, errors are not being passed here: 
https://github.com/middyjs/middy/blob/1d04aefd2a5cc8b16e3820bc0ca1d0654c3d3d92/src/middlewares/cors.js#L50
resulting in success callbacks and response of 200 empty body.
When used with other middlewares such as the `httpErrorHandler`, the non-http errors do not have a chance to be converted to an http response and are passed along and when using in addition with `cors`, the error is swallowed and the callback is called without an error resulting in a 200 response with an empty body.
This change allows any errors to be passed to the next middleware by `cors` if any and gives the user a chance to handle the error or if there is no further …
=> Prevent Cors middleware swallowing errors

package-lock.json, package.json, src/middlewares/__tests__/ssm.js, src/middlewares/ssm.js
The SSM middleware currently has a bug where, when using names to access SSM parameters, the last of multiple names pointing at the same SSM parameter will overwrite the others.
E.g. with the following middleware options, only `KEY_NAME_2` will be set.
```javaScript
names: {
KEY_NAME_1: '/dev/service_name/key_name',
KEY_NAME_2: '/dev/service_name/key_name'
}
```
This PR fixes this bug and deduplicates the SSM parameters which are being accessed by name so that in the above scenario, `/dev/service_name/key_name` is fetched exactly once and then set onto both `KEY_NAME_1` and `KEY_NAME_2`.
=> Bug fix: Allow multiple environment variables to be set to the same SSM parameter via name

docs/middlewares.md, package-lock.json, package.json, src/middlewares/__tests__/httpErrorHandler.js, src/middlewares/httpErrorHandler.js
If the code is mangled during minification process when using webpack, the check for a type of `HttpError` in the httpErrorHandler middleware will fail. As the private property on `super_.name` will not be `HttpError`, the mangling would change the name.
This is due to [Terser](https://github.com/webpack-contrib/terser-webpack-plugin) setting both `keep_classnames` and `keep_fnames` to false by default.
Either way it shouldn't really use a private property to check the type of error.
This will close https://github.com/middyjs/middy/issues/325
=> fix: httpErrorHandler minification type checking

README.md, README.md.hb, package-lock.json, package.json
I think the `urlEncodeBodyParser` isn't supposed to be used here. Use `jsonBodyParser` instead.
=> Fix typo in the appetizer in README.md

docs/middlewares.md, middlewares.d.ts, package-lock.json, package.json, src/middlewares/__tests__/warmup.js, src/middlewares/warmup.js
This is required when using both `warmup` & `doNotWaitForEmptyEventLoop`.
=> Update warmup.js to work alongside with doNotWaitForEmptyEventLoop

README.md, README.md.hb, package-lock.json, package.json
Clarify the behavior of promise-enabled error handlers
=> Update the documentation

index.d.ts, package-lock.json, package.json
These changes needed to make it possible (and easier) to extend context in runtime with typescript support.
So now we can use it like this: 
```ts
// Defining our extended type of the context
export interface ContextWithExtraArgs extends Context {
extra?: ExtraType;
}
const before: MiddlewareFunction<SQSEventWithLogger, Response, ContextWithRecords> = ({
event,
context,
}) => {
context.extra = someExtraValue;
};
const withExtraArgs: MiddlewareObject<SQSEventWithLogger, Response, ContextWithRecords> = {
before,
};
const originalHandler = async (event: SQSEvent, context: ContextWithExtraArgs): Promise<void> => {
// now we can use extra args here and typescript will happy as well
console.log(context.extra);
};
const handler = applyMiddleware(originalHandler).use(withExtraArgs);
```
Thanks.
=> TS: Make it possible to extend context type with typescript

README.md, package-lock.json, package.json
Just fixing a few spelling & grammar issues I encountered when reading through the docs.
=> Small spelling fixes

README.md, README.md.hb, package-lock.json, package.json
In the TOC section of the readme, the link to `Q: Lambda timing out` is not working, this PR fixes that link.
The other changes are a result of me executing `npm run build` to test my changes and finding the changes made in https://github.com/middyjs/middy/pull/406 were only applied to README.md and not README.md.hb
=> Documentation Improvements

README.md
#using-async-await is not compatible herf link to `Using async/await`
to link properly, it should use #using-asyncawait
=> fix broken link href in readme

index.d.ts, package-lock.json, package.json
Hey @lmammino,
Right now even though some packages rely on context modification you can't change it and use TypeScript in the same time.
I have changed typings so now your custom context is visible in TypeScript, without this change your middleware functions need to have format `HandlerLambda<never, never, CustomContext>`.
Cheers
=> [TypeScript] Ability to set your own context

README.md, README.md.hb, package-lock.json, package.json
Adds a warning in the README on master (currently 0.x) to start suggesting users to move to 1.0.0-beta.
It also proposes a timeline for future releases and version management.
=> Add deprecation warning in README - switch to 1.0.0-beta

README.md
Add a FAQ item about the `context.done called twice within handler` warning in the main README file. This warning happens when you try to use callbacks (`callback()` or `next()` functions) inside async handlers or middlewares, and is kinda hard to debug. Hopefully this addition to the docs will be indexed by Google and future devs who stumble in this problem will be able to solve it much quicker than I did.
[Issue #480 ](https://github.com/middyjs/middy/issues/480)
Todo list
---------
=> Add FAQ item about context.done called twice warning

src/__tests__/middy.js, src/middy.js
Changed run error middlewares so that it conforms to the behaviour stated in the documentation
```javascript
middleware1 = {
onError: (handler) => {
handler.response = { error: handler.error };
return Promise.resolve();
// Resolves to a falsy value
}
}
middleware2 = {
onError: (handler) => {
return Promise.resolve(handler.error)
}
}
handler.use(middleware1).use(middleware2);
```
`middleware2` should not be called.
- #485
=> Changed error handling logic to stop after error has been handled

packages/input-output-logger/README.md, packages/input-output-logger/__tests__/index.js, packages/input-output-logger/index.d.ts, packages/input-output-logger/index.js, packages/input-output-logger/package-lock.json, packages/input-output-logger/package.json
Adds the ability to exclude paths from input/output logger.  
Very useful to reduce log verbosity and scrub-off secrets or sensitive data.  
**Node.js Versions:** v12.16.1
**Middy Versions:** 1.0.0-beta
**AWS SDK Versions:** 2.556.0
Todo list
---------
=> Ability to exclude paths in input-output-logger

packages/db-manager/README.md
Fix badge URL of [@middy/db-manager](https://github.com/middyjs/middy/tree/master/packages/db-manager)
no
no
no
no
Todo list
---------
=> docs(db-manager): fix Markdown syntax for link

packages/http-header-normalizer/index.js
`options.canonical` is only respected for single value headers. When it is set, multi value headers get lowercased.
Fixes #475 
Logging `event` (shortened for brevity):
```
headers: {
Host: 'localhost:3000',
'Accept-Encoding': 'gzip, deflate',
DNT: '1',
},
multiValueHeaders: {
host: [ 'localhost:3000' ],
'accept-encoding': [ 'gzip, deflate' ],
DNT: [ '1' ],
}
```
**Node.js Versions:** not sure
**Middy Versions:** 1.0.0
**AWS SDK Versions:** not sure
Todo list
---------
[x] …
=> [http-header-normalizer] Respect canonical normalisation parameter for multiValueHeaders

packages/http-multipart-body-parser/__tests__/index.js, packages/http-multipart-body-parser/index.js
When receiving formdata with an array (eg. checkboxes), only the last value is used. A simple way to test is by trying out the following:
```
curl -X POST -F 'foo[]=one' -F 'foo[]=two' http://localhost
```
Currently this would parse as
```
'foo[]': 'two'
```
With this change, the result is:
```
'foo': [ 'one', 'two' ]
```
No
n/a
I originally created #508 but rebasing was causing some issues on my end. Made a clean branch and put the changes here instead. …
=> [http-multipart-body-parser] Parse array from multipart form data

packages/http-multipart-body-parser/index.js
Busboy includes a boolean for a truncated file upload. I need that, so I'm adding it into the appropriate package.
No idea.
Nope.
See issue and a link to the docs here:
https://github.com/mscdex/busboy/issues/76
**Node.js Versions:** v12.16.2
**Middy Versions:** 1.0.0
**AWS SDK …
=> Add the boolean check for a truncated file upload

packages/http-json-body-parser/__tests__/index.js, packages/http-json-body-parser/index.js
The [input of a Lambda](https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html) function can be encoded with base64. This PR handles base64 encoded events on the `http-json-body-parser` middleware.
No
No
No
**Node.js Versions:** 12.13.1
**Middy Versions:** 1.0.0
**AWS SDK Versions:** 2.689.0
Todo list
---------
[x] Updated relevant …
=> Handling base64 event bodies

packages/db-manager/index.d.ts
[[@middy/db-manager](https://github.com/middyjs/middy/tree/master/packages/db-manager)] Provide default type definition like [@middy/secrets-manager](https://github.com/middyjs/middy/blob/master/packages/secrets-manager/index.d.ts).
Then, default import  is available in TypeScript.
```ts
import middy from '@middy/core'
import lambda from 'aws-lambda'
import Knex from 'knex'
import dbManager from '@middy/db-manager'
interface Context extends lambda.Context {
db: Knex
}
const handler = middy(async (
event: any,
context: Context,
callback: lambda.Callback<any>
): Promise<void> => {
const { db } = context
const users = await db.select('*').from('users')
console.log(users)
}) …
```
=> fix(db-manager): improve type definition

packages/http-response-serializer/__tests__/index.js, packages/http-response-serializer/index.js
And all the `opts.serializers` too.
[`Array.prototype.find`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find) short circuits on truthy return values of its callback, which means that we only would've ever traversed the array for the first element of `types` since `opts.serializers.map` just returns an array of booleans right?
Fix this typo and add a test to cover my use case of wanting to fall back to a default if no preferred serializer is found.
Nothing that I could find from my quick searching. I just needed this for myself right now.
Any relevant logs, …
=> The `httpResponseSerializer` needs to find a serializer for a `type` by searching all the `types`

packages/http-event-normalizer/README.md, packages/http-event-normalizer/__tests__/index.js, packages/http-event-normalizer/index.d.ts, packages/http-event-normalizer/index.js
Add new option for http-event-normalizer to enable use of  API Gateway HTTP API payload format v2.0 event.
This middleware "recognize" incoming event from API Gateway using the existence of `httpMethod` parameter on input event object. With HTTP API v2.0, this parameter does not exist anymore, and is replaced with `requestContext.http.method`
No
No
No
**Node.js Versions:** 12
**Middy Versions:** 1.0.0
**AWS SDK Versions:** N/A
Todo …
=> Add support for API Gateway HTTP API payload format v2.0 in http-event-normalizer middleware

packages/ssm/README.md, packages/ssm/__tests__/index.js, packages/ssm/index.d.ts, packages/ssm/index.js
The `onChange` support for SSM middleware was missed from the 0.x branch, this PR adds it back in.
No.
No.
Todo list
---------
[x] …
=> feat: add ssm.onChange support back to 1.x

README.md
Fixes the url for guide for upgrading from 0.x to 1.x + points to the latest stable release tree.
Yes. https://github.com/middyjs/middy/issues/554
…
**AWS SDK …
=> docs: correct url to guide for upgrading from 0.x to 1.x

packages/validator/README.md, packages/validator/__tests__/index.js, packages/validator/index.d.ts, packages/validator/index.js, packages/validator/package-lock.json, packages/validator/package.json
Implements the ability to apply passed plugins to validator
Closes #550 
N/A
N/A
**Node.js Versions:** 12.16.1
**Middy Versions:** 1.2.0
**AWS SDK Versions:** 2.656.0
Todo list
---------
[x] Updated …
=> Validator accepting plugins

packages/core/__tests__/index.js, packages/core/index.js
middlewares should be able to change the context that is passed to handlers
#484 
…
Todo list
---------
[X] Feature/Fix fully implemented …
=> fix(core): before middlewares should be able to change context

packages/input-output-logger/__tests__/index.js, packages/input-output-logger/index.js
… and unit test with the case.
----------------------------------------------------
While working with the middleware I discovered that, when adding a path to omitPaths which is apart of an array ("response.users[0].email"), the field was deleted form the log but also from the response.
Using cloneDeep fixes this behaviour (unit test added).
…
Any other …
=> Add lodash cloneDeep to support arrays in omitPaths

packages/core/__tests__/index.js, packages/core/index.js
Fixes -> https://codesandbox.io/s/purple-star-n3ohc?file=/src/index.js
This scopes the request object to an individual request.  This allows for calling a wrapped handler multiple times concurrently.  This is useful when trying to reuse individual handlers when batching.  Without this a handler may receive the wrong request or return the incorrect response when calling concurrently.
https://github.com/middyjs/middy/issues/558
This could be considered a breaking change if someone was mutating the handler object intending it to persist between requests.  
That …
=> Scope each request independently

packages/validator/index.js
In order to instruct webpack to take into account certain required modules in a dynamic fashion, the path should be explicit. So first the conventional way to get the library is tried, if it fails, the code tries to go with an explicit path to the main file for the library.
Closes #560 
N/A
N/A …
=> Explicit path on implicit require error

packages/http-json-body-parser/__tests__/index.js, packages/http-json-body-parser/index.js
This change the http-json-body-parser to also automatically accept request
bodies that have a media type like 'application/vnd+json'
This augments the http-json-body-parser to also automatically parse any request bodies that have a JSON
content type that is included like a suffix. For example "application/vnd.api+json".
For more information please see [RFC 6839](https://tools.ietf.org/html/rfc6839)
… …
=> feat: http-json-body-parser handles JSON Media Type Suffix

packages/ssm/README.md, packages/ssm/index.d.ts, packages/ssm/index.js
Adds support for customising the SSM instance used by the @middy/ssm middleware. The purpose of doing this is to enable tracing tools to add hooks to the instantiated instance, such as AWS XRay.
No
N/A
**Node.js Versions:** nodejs 12.x
**Middy Versions:** version in master
**AWS SDK Versions:** 2.772.0
Todo list
---------
[ X ] Feature/Fix fully implemented
[ N/A ] Added tests
[ X ] Updated relevant documentation
[N/A] Updated …
=> feat: customisable aws-sdk instance of SSM

packages/ssm/README.md, packages/ssm/__tests__/index.js, packages/ssm/index.d.ts, packages/ssm/index.js, packages/ssm/package-lock.json
…
PR regarding #567 
If you provide a non-existent SSM parameter to the `@middy/ssm` middleware it will cause the function to go to timeout if you are not using `@middy/do-not-wait-for-empty-event-loop`, or with  `do-not-wait-for-empty-event-loop` in place, it will fail immediately (the error is thrown in the `handleInvalidParams()` function but it is not handled anywhere!) and not reach the original handler!
Changes: 
- Added optional `throwOnFailedCall` flag with default value `false` (Same implementation as Secret Manager middleware)
- Added catch to the main Promise.all(ssmPromises)
- If  `throwOnFailedCall=false` it will just `console.error` the error and continue to the next …
=> Prevent lambda timeouts or failure from not handled promise due to invalid SSM parameter(s)... Add throwOnFailedCall flag to the SSM middleware 

README.md
Adds [`middy-lesslog`](https://github.com/rschweizer/middy-lesslog) as a new entry to the list of community middlewares in the README.
No
No
**Node.js Versions:** 8.x
**Middy Versions:** 1.x
**AWS SDK Versions:** not relevant
=> Add `middy-lesslog` to community middlewares

package.json, packages/validator/index.js
`require()` staments that use string interpolation are not compatible with `esbuild` unless the code is surrounded with a try-catch block.
No
```
Serverless: Compiling with esbuild...
> node_modules/@middy/validator/index.js: warning: This call to "require" will not be bundled because the argument is not a string literal (surround with a try/catch to silence this warning)
124 │       const pckJson = require(`../../ajv-${p}/package.json`)
╵                       ~~~~~~~
> node_modules/@middy/validator/index.js: warning: This …
```
=> Fix esbuild compatibility issue

packages/http-urlencode-body-parser/__tests__/index.js, packages/http-urlencode-body-parser/index.js
This PR automatically decode base64 body for API Gateway v1 and v2 payloads before parse urlencoded body.
No
**Real world exemple**
When setting up Slack command endpoint to an HTTP API Gateway, the event body passed to the invoked lambda is encoded in base64 by API Gateway. The event body, as stated in the [Slack documentation](https://api.slack.com/interactivity/slash-commands#app_command_handling), is stringified in url encoded format. The @middy/http-urlencode-body-parser middleware needs first to decode base64 content : …
=> Add base64decode on http urlencode body parser middleware

packages/http-multipart-body-parser/README.md
Edit sample of @middy/http-multipart-body-parser
No
```
TypeError: httpMultipartBodyParser is not a function
```
It's kinda weird that this thing stays here without any complaints for quite a long time. Please correct me if I'm getting something wrong here. But I believe this is the correct way to import. …
=> fix: sample import code of http-multipart-bodyparser README

packages/http-multipart-body-parser/__tests__/index.js, packages/http-multipart-body-parser/index.js
Single key with multiple file parser, but the key is not annotated with array:
Pseudo code for the request on client site:
```js
const formData = new FormData()
fileList.forEach((file) => {
formData.append('files', file)   // no [] here
})
reqwest({
url: 'http://localhost:3000/upload',
method: 'post',
data: formData,
// others
}
```
No
(If it’s long, please paste to …
=> add: http-multipart-body-parser parse single keys with multiple files

.github/workflows/tests.yml, packages/core/index.d.ts, packages/core/index.test-d.ts
With current Typescript definition it is not possible to locally execute the handler function, either from a local file to debug, or from unit tests, without getting a Typescript error:
```
This expression is not callable.
Type 'MiddyfiedHandler<APIGatewayProxyEvent, APIGatewayProxyResult, Error>' has no call signatures.
```
I believe the issue is that the Typescript definition of the `MiddyfiedHandler` does not extend the Lambda Handler so is not a callable function.
Fix is to add `LambdaHandler` to the `MiddyfiedHandler` interface definition. 
closes #628  …
=> fix: fix typing on core middy handler

packages/ssm/index.js
Infinite loop in @middy/ssm caused by typo recursion logic.
No.
fetchPath would infinitely iterate when there were > 10 parameters because the nextToken was undefined.  Below is a test case with 11 parameters.
```
//const fetchPath = (path, nextToken, values = {}) => {
fetchPath i:0, nextToken: undefined, values length: 0
fetchPath i:1, nextToken: undefined, values length: 10
fetchPath i:2, nextToken: undefined, values length: 10
fetchPath i:3, nextToken: undefined, values length: 10
...
```
After:
```
fetchPath i:0, nextToken: …
```
=> fix: correct typo in SSM package.

packages/secrets-manager/README.md
Fixes and clarifies Secrets Manager middleware example. The names of the secrets and the resulting context were incorrect and causing confusion. Also added missing parameters to the middleware to clarify its usage.
Todo list
---------
=> docs: fix typos and clarify example

packages/http-response-serializer/README.md, packages/http-response-serializer/__tests__/index.js, packages/http-response-serializer/index.js
In an attempt to address #657, `body` was checked to determined wether or not the entire response should be replaced (by @willfarrell).  
The problem with that fix is that any falsy value in `body` would not replace the entire response as well (think `false`, 0, or even `null` or `undefined` body).  
Resolves #657 
x
x
**Node.js Versions:** 14
**Middy Versions:** 2.1.0
Todo list
---------
=> Fix: Response Serializer does not replace entire object when falsey value is returned

packages/validator/index.js
Fixing an integration test issue when multiple lambda handlers are invoked in a single run. 
`ajvOptions` of subsequent lambda handlers for the validator are ignored if the `ajv` object is compiled already. This is a simple fix to force the `ajvOptions` to be overwritten.
I don't know
Here is a link to the git repo to illustrate the issue:
https://github.com/qualipsolutions/middy-test
Clone the repo, then:
1. `yarn`
2. `yarn server`
`app.js` imports two lambda functions. The first lambda import causes the `ajv` to be compiled …
=> fix: :bug: Fixing an integration test issue

packages/core/index.d.ts
Exporting the interfaces directly gives the users of the middy package the flexibility to choose how they would like to import.
fixes #645
Does not impact any functional behaviour of middy
=> Export middy interfaces directly

README.md
Updates `middy-lesslog` entries in the list of community middlewares in the README.
No
No
No
**Node.js Versions:** 12.x and 14.x
**Middy Versions:** 1.x and 2.x
**AWS SDK Versions:** not relevant
=> Update `middy-lesslog` in community middlewares

packages/core/__tests__/index.js, packages/core/index.js
When an error was unhandled by the error middleware, it was being re-thrown and added to itself. 
This was causing issues with downstream testing libraries which JSON.stringify the error and blow up as it's a circular dep.
Polluting logging having duplicate errors inside itself.
No
CI/CD
Todo list
---------
[TODO ] Added tests
=> fix(core): moving unhandled error throw

packages/http-cors/README.md
Updates documentation for the @middy/http-cors `credentials` option.
No.
I'm not sure about the original documentation. The `getOrigin` function also [does something](https://github.com/middyjs/middy/blob/main/packages/http-cors/index.js#L11) with `options.credentials` but I feel like the information that the `Acess-Control-Allow-Credentials` is also being set with this is certainly missing. I am happy to rephrase the line to also talk about the change to `Origin` if required.
Where has …
=> Update http-cors `credentials` documentation.

packages/input-output-logger/index.d.ts, packages/input-output-logger/index.test-d.ts
It fix `index.d.ts` of `@middy/input-output-logger` to support `awsContext`.
No.
N/A
N/A
**Node.js Versions:** 16.2.0
**Middy Versions:** 2.4.2
Todo list
---------
=> types(input-output-logger): support awsContext

packages/ssm/README.md
This PR updates the Middy SSM README description on assigning to process.env. According to the options section, `setToEnv` is default `false`. So it's misleading to say that params are assigned Process.env by default.
I don't think so.
N.A. 
N.A. 
**Node.js Versions:** N.A. 
**Middy …
=> docs: update middy SSM description on assigning to process.env

packages/http-error-handler/__tests__/index.js, packages/http-error-handler/index.js, packages/http-response-serializer/__tests__/index.js
This fixes text responses with the correct mime type assigned for them (text/plain).
=> fix: Content-Type misspelling

packages/core/index.d.ts, packages/core/index.test-d.ts
Some middleware adds extra fields to the context. Typescript will complain if the fields are not declared optional, even if the middleware guarantees they are set before invoking the next step. With this pull request you can specify a custom Context type, including those fields.
This is not yet fully automated inference of the Context type by combining types from each middleware (see https://github.com/middyjs/middy/issues/589) but rather a first step towards it. You still have to update the type manually as you add/remove middleware.
The …
=> Typescript: Typed Context

packages/util/index.d.ts
Added type for `createError` function.
Closes #700 
N/A
N/A
Todo list
---------
=> fix: added type for createError function

packages/core/index.d.ts, packages/core/index.test-d.ts
Fixes #703.
A few things have changed with the types:
1. `MiddyInputHandler` is now a copy of `Handler` from `aws-lambda` but with a generic context
2. Updated the default value of the generic context from `any` to `Context` to align it with `aws-lambda`
3. Removed typings that didn't seem necessary anymore.
Testing:
Changed the base handler to be an `aws-lambda` `Handler` type.
I'm getting some lint errors from the using `void` in the return type, but that's what `aws-lambda` `Handler` uses.
How do I ignore these?
```
ts-standard: Typescript Standard Style! (https://github.com/standard/ts-standard) …
```
=> TypeScript: Align types with aws-lambda

README.md
This adds documentation on how to write a Typescript middleware using middy. This has no code changes or behavior changes but I had to search for the type definitions to be able to implement a custom middleware in a recent project. I think adding an example would be helpful to someone in the same situation.
It does not close it but is related to #589 
Not applicable given that this is an documentation change.
I noticed opening this PR that my text editor removed some trailing white …
=> Add example of a middleware written in Typescript

packages/util/index.d.ts
We use the modify cache function and it's missing type declarations.
Doesn't close any issues but adds to the type system as help was needed
…
Todo list
---------
=> fix: :label: Added missing types for `modifyCache`

packages/sqs-partial-batch-failure/__tests__/index.js, packages/sqs-partial-batch-failure/index.js
#722 
AWS' [deleteMessageBatch](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_DeleteMessageBatch.html) API only supports 10 messages per request.  This PR chunks up entries in groups of 10 in order to support larger batch es.  
#722 
This bug only surfaces when there is a group of more than 10 messages and at least one failure. …
=> fix: Chunk deleteMessageBatch requests. Fixes #722.

packages/http-json-body-parser/README.md, packages/http-json-body-parser/__tests__/index.js, packages/http-json-body-parser/index.js
For webhook signature validation, and other use cases, it is important to be able to access the original raw body. This is because parsing it as JSON loses information about whitespace etc. that may be important for things like cryptographic signatures.
Closes #740 
I've been using this in my own projects and it seems to be working well. I've found it useful for integrating with Slack and Stripe webhooks. For me, exposing this rawBody is preferable to adding middleware before the JSON parsing middleware as I want to be able to use standard middleware and be …
=> http-json-body-parser: Add rawBody to event

packages/http-cors/README.md
This is a small typo fix
No
Not Required
No
=> docs: fix typo

README.md
…
…
…
Todo list
---------
[ ] Updated relevant …
=> Move `middy-event-loop-tracer`, `middy-console-logger` and `middy-invocation` middlewares into  `Version 2.x` section in README

packages/core/index.d.ts
It seems that it was overlooked because `TContext` is passed to `MiddyfiedHandler.onError`.
It fixes type definition for MiddlewareObj.onError
IDK
NA
NA
**Node.js Versions:** 16
**Middy Versions:** 2.5.3
**AWS SDK Versions:** NA
Todo list
---------
=> Pass TContext to the onError handler definition

benchmark/tests/looping.js, packages/http-multipart-body-parser/__tests__/index.js, packages/http-multipart-body-parser/index.js, packages/sqs-partial-batch-failure/index.js
Fix the lint issue which break the pipeline already (https://github.com/middyjs/middy/runs/4638685138?check_suite_focus=true)
No, but it will fix the pipeline "Lint" action.
…
**Middy …
=> fix(lint): disable "no-empty" rule  in looping.js and fix lint issues.

packages/validator/__tests__/index.js, packages/validator/index.js
This change is to fix the i18n for Chinese simplified `zh`,  for `zh`, the ajv i18n language should be `zh`, not `zh-TW` which is for Chinese traditional. 
FYI https://github.com/ajv-validator/ajv-i18n/blob/master/messages/index.js#L612
No.
…
Where has this been …
=> fix(zh): The zh-TW is not for zh, it's should be zh (#1)

packages/sqs-partial-batch-failure/index.js, packages/sqs-partial-batch-failure/package.json
It passes Error Stack along with message.
No
Currently, if any worker gets shared by multiple methods, then it's very difficult (sometimes impossible without running locally) to pinpoint the exact location where the error occurs. Hence adding the original stack of the error.
**Node.js Versions:** 14.17.6
**Middy Versions:** 2.5.3
**AWS SDK Versions:** ^2.1014.0
=> Sqs batch failure error stack

packages/http-content-encoding/README.md, packages/http-content-encoding/__tests__/index.js, packages/http-content-encoding/index.d.ts, packages/http-content-encoding/index.js, packages/http-content-encoding/index.test-d.ts, packages/http-content-encoding/package.json
=> New Middleware: http-content-encoding

packages/validator/README.md, packages/validator/__tests__/index.js, packages/validator/index.d.ts, packages/validator/index.js, packages/validator/index.test-d.ts
Adds a flag to disable localization. Must-have for ajv-errors working as-is from 1.x versions
Big codebases can have huge troubles to migrate from 1.x version to 2.x versions without such option
Not really, simple enhancement of the 2.x version to be more flexible 
`"must pass \"errorMessage\" keyword validation"`
Message popping up with i18n enabled and attempt to use ajv-errors 
**Node.js Versions:** 
14
latest
latest
[ X ] …
=> Add posibility to use ajv-errors without i18n

packages/http-cors/index.d.ts, packages/http-cors/index.test-d.ts
This PR adds the `getOrigin` option to the `index.d.ts` file, enabling the TypeScript applications to use the `getOrigin` option.
#774 
**Node.js Versions:**
- v12.22.2
**Middy Versions:**
- v2.5.4
**AWS SDK Versions:**
- node14x Lambda runtime AWS SDK version.
Todo list
---------
=> [#774] `@middy/http-cors` TypeScript getOrigin

docs/patterns/aws-alb-event.js, packages/http-router/README.md, packages/http-router/__tests__/index.js, packages/http-router/index.d.ts, packages/http-router/index.js, packages/http-router/index.test-d.ts, packages/http-router/package.json
- All methods & `ANY`
- pathParameters (`/{id}`)
- wildcards (`/{proxy+}`)
- no 3rd party dependencies
- stupid fast, no seriously
```
=======================
find-my-way benchmark (used by fastify & restify)
=======================
short static: 15,692,685 ops/sec
static with same radix: 5,149,892 ops/sec
dynamic route: 2,255,178 ops/sec
mixed static dynamic: 2,821,514 ops/sec
long static: 6,370,850 ops/sec
wildcard: 3,677,858 ops/sec
all together: 642,840 ops/sec
==============================
@middy/http-router benchmark
==============================
short static: 32,834,799 ops/sec
static with same radix: 37,876,469 ops/sec
dynamic route: 15,235,551 ops/sec
mixed static dynamic: 9,714,873 ops/sec
long static: 39,087,567 ops/sec
wildcard: 6,236,354 ops/sec
all together: 2,406,433 …
```
=> v3: HTTP Router

packages/input-output-logger/index.d.ts
The fields `mask` and `replacer` are missing in the `Option` interface. I have added the missing fields to provide typescript type information.
=> fix: Add missing fields to Option typescript type

website/docs/intro/01-intro.md, website/docs/intro/02-getting-started.md, website/docs/intro/06-typescript.md, website/docs/middlewares/sqs-partial-batch-failure.md
Very minor typo: lambdaHander 👉 lambdaHand**l**er
=> docs: fix handler typo

packages/http-error-handler/index.d.ts
Fix error `Type 'boolean' is not assignable to type '(error: any) => void'.`
According to [readme](https://github.com/middyjs/middy/tree/main/packages/http-error-handler#options), "You can pass `false`" to the `logger` option
=> fix(http-error-handler): type error in 'logger' option

packages/http-response-serializer/index.d.ts
Ran into this while debugging middlewares.
Thanks for all the hard work on middy! 
🥳
=> fix(http-response-serializer): type typo

packages/http-response-serializer/index.d.ts
The type was inferred from this test: https://github.com/middyjs/middy/blob/8ec3224e773ff6938ab446ad6335091b2a99a3c2/packages/http-response-serializer/__tests__/index.js#L257
=> fix(http-response-serializer): add type for full-response serializers

packages/http-router/index.d.ts
Struggled to type the `ROUTES` array mainatined in a configuration file that gets imported for the httpRouter
=> fix: export route and method for middy http router

packages/core/index.d.ts
In the middy 3, we proposed the `.handler` function but not mentioned in the type for `TypeScript`. This change is adding to that.
=> fix(type): add `handler` in the `MiddyfiedHandler`

docs/UPGRADE.md, packages/http-error-handler/README.md, packages/http-response-serializer/package.json, website/docs/middlewares/http-error-handler.md, website/docs/upgrade/1-2.md
updated occurrences of "reponse" to "response"
=> fixed typo in documentation

website/docs/middlewares/http-event-normalizer.md
=> docs: remove payloadFormatVersion option in @middy/http-event-normalizer

packages/http-router/index.d.ts, packages/http-router/index.test-d.ts
httpRouterHandler should return a MiddyfiedHandler to be type-checked correctly
=> Fix TS Error in httpRouterHandler

packages/rds-signer/index.d.ts, packages/rds-signer/index.test-d.ts, packages/s3-object-response/index.d.ts, packages/s3-object-response/index.test-d.ts, packages/secrets-manager/index.d.ts, packages/secrets-manager/index.test-d.ts, packages/service-discovery/index.d.ts, packages/service-discovery/index.test-d.ts, packages/sqs-partial-batch-failure/index.d.ts, packages/sqs-partial-batch-failure/index.test-d.ts, packages/ssm/index.d.ts, packages/ssm/index.test-d.ts, packages/sts/index.d.ts, packages/sts/index.test-d.ts, packages/util/index.test-d.ts, packages/ws-response/index.d.ts, packages/ws-response/index.test-d.ts
In order to reduce check-types we should import the submodule directly.
This method is already in use for the main `js` files, but not for the `.d.ts` files - so we pay the price when typechecking our code.
- importing the whole aws-sdk takes 3.5 seconds of typechecking time.
You can see 2.5 seconds in the picture below, but there is added segment of binding operations that takes another ~second
=> Use aws-sdk submodule

website/docusaurus.config.js
The GitHub link in the footer wasn't changed and still pointed to the docusaurus repository instead of the middy repository.
=> Change GitHub link in documentation from docusaurus to middy

website/docs/middlewares/validator.md
ajv requires the schema to specify its type when running in strict mode.
The examples in the docs do not have that, and thus they fail with the following error:
```haskell
Error: strict mode: missing type "object" for keyword "required" at "#" (strictTypes)
at checkStrictMode (~/node_modules/.pnpm/ajv@8.11.0/node_modules/ajv/dist/compile/util.js:174:15)
at strictTypesError (~/node_modules/.pnpm/ajv@8.11.0/node_modules/ajv/dist/compile/validate/index.js:275:32)
at checkKeywordTypes (~/node_modules/.pnpm/ajv@8.11.0/node_modules/ajv/dist/compile/validate/index.js:261:17)
at checkStrictTypes (~/node_modules/.pnpm/ajv@8.11.0/node_modules/ajv/dist/compile/validate/index.js:233:5)
at schemaKeywords (~/node_modules/.pnpm/ajv@8.11.0/node_modules/ajv/dist/compile/validate/index.js:189:9)
at …
```
=> [docs][@middy/validator] Add missing type "object"

website/docs/middlewares/http-response-serializer.md
In the new version of http-response-serializer middleware  the `default` option is renamed to `defaultContentType`
=> Update http-response-serializer default option to defaultContentType

packages/http-security-headers/index.d.ts, packages/http-security-headers/index.test-d.ts
Hi! 
I started recently using security-headers with typescript and noticed that type definitions don't quite match the javascript implementation. Here are some fixes that allow typescript usage without using `// @ts-ignore`. 
Basically this allows typescript users to pass in false to skip setting header and adds some recently added headers.
=> Improve typings for security-headers middleware

.github/workflows/release.yml
This pull request fixes the CommonJS export in version 3.2.1 due to a change in https://github.com/swc-project/swc/releases/tag/v1.2.206 (https://github.com/swc-project/swc/issues/5204)
Version 3.2.1:
```
Object.defineProperty(module, "exports", {
enumerable: true,
get: ()=>_default
});
```
Version 3.2.0:
```
module.exports = _default;
```
=> Fix CommonJS export in version 3.2.1

packages/http-response-serializer/README.md
There's a typo in the sample usage that trips up first time users of the `@middy/http-response-serializer`  so updated the top example to be consistent with the others.
=> docs: replace typo `default` in sample with `defaultContentType`

packages/util/index.d.ts, packages/util/index.test-d.ts
- Changed the return type of `createClient` to be a Promise.
- Made `request` an optional argument in `processCache` to work for scenarios like prefetching where there is no request.
=> Minor fixes in utility types

website/docs/intro/06-typescript.md
Remove 'handler' word incorrectly placed within code sample.
=> :memo: middy wrapped handler syntax error

packages/http-multipart-body-parser/README.md, packages/http-multipart-body-parser/__tests__/index.js, packages/http-multipart-body-parser/index.d.ts, packages/http-multipart-body-parser/index.js, packages/http-multipart-body-parser/index.test-d.ts, website/docs/middlewares/http-multipart-body-parser.md
Related to #932
This seemed like something I could contribute to, please let me know if I missed anything
=> feat: add optional charset option to multipart body parser

packages/core/index.d.ts
**Issue:** https://github.com/middyjs/middy/issues/933
Exports the [Request](https://github.com/middyjs/middy/blob/main/packages/core/index.d.ts#L24) interface so that consumers can assign the type to the argument in the middleware functions.
```ts
const middlewareObj = {
before: (request: Request) => {
...
}
}
```
=> Export the Request interface

packages/core/index.d.ts
Useful if middleware adds properties to the event.
e.g.
A `authMiddleware` that adds `userId` from a JWT token to the event.
`handler<{userId: string}>(event => event.userId)` <-- userId will not complain in TS.
=> Allow handler setup to define additional properties on event

website/docs/best-practices/05-bundling.md
AWS themselves [recommend ](https://docs.aws.amazon.com/lambda/latest/operatorguide/sdks-functions.html)that you always bundle the `aws-sdk` with your project.
Using the build-in sdk should be limited to quick tests and is not suitable for production use.
=> Update 05-bundling.md recommendation on bundling the aws-sdk

website/docs/middlewares/validator.md
This pull request replaces the `inputSchema` option that is deprecated according to the [4.x upgrade guide](https://middy.js.org/docs/upgrade/3-4/#validator). It has also been removed from the TypeScript definitions in https://github.com/middyjs/middy/commit/2a9154ff056ab06f871f2f1ca34393f99df3d0d3.
=> Replace deprecated validator option

packages/event-normalizer/__tests__/index.js, packages/event-normalizer/index.js
According to Lambda [documentation](https://docs.aws.amazon.com/lambda/latest/dg/with-kafka.html) event source name for self-managed Apache Kafka is `SelfManagedKafka` *not* `aws:SelfManagedKafka`.
I found this by enabling `@middy/event-normalizer` middleware for my project with this event source type and noticed that the event normalizer does not Base64 decode the record value. Made a fork with fixed event source name and now it works as expected.
=> fix: self-managed kafka event source name

packages/http-router/index.d.ts
- update generics for httpRouterHandler
- add ALBEvent to generic extends list
Resolves Issue #955
https://github.com/middyjs/middy/issues/955
TODO:
=> Update http-router type defs

packages/http-router/index.d.ts, packages/http-router/index.test-d.ts
Addresses [this comment](https://github.com/middyjs/middy/issues/895#issuecomment-1344252536) in #895.
Exposes the `Method` type as a String Enum instead of a union string.
Note that this is a breaking TS change as per the linked comment.
=> Feature: http-router - Expose Method as a string-enum.

packages/http-router/__tests__/index.js, packages/http-router/index.js
when creating pathParameters in a dynamic route, the resulting object is a `null prototype` object which causes problems for libraries that try to inspect pathParameters using prototype methods
this patch creates pathParameters as a "full fledged" object
=> make event.pathParameter a full object

packages/http-router/__tests__/index.js, packages/http-router/index.js
Previous code only wrote `pathParameters` in the event for a dynamic route when existing `pathParameters` property was undefined, this PR fixed that and merges both existing `pathParameters` and the inferred from the dynamic route
=> merge existing event.pathParameters with the ones inferred from the dynamic route

packages/core/__tests__/index.js, packages/core/index.js
This pull request addresses an issue where the handler timeout is not being correctly aborted when the handler either succeeds or fails.
This leads to the lambda handler and the timeout handler being both called instead of just one of them. This is a problem if the timeout handler produces side effects (for example, logging)
Let me know if you have any questions or concerns, regards!
=> Abort the handler timeout when the handler succeeds or fail

packages/http-cors/index.d.ts, packages/http-cors/index.js, packages/http-cors/index.test-d.ts, packages/http-cors/package-lock.json, website/docs/middlewares/http-cors.md
This feature (default -> true) handles all OPTION requests from a cors enabled browser automatically. Since a lot of people have problems understanding cors, i made it default to true. Only problem which might arise is if somebody really wants to handle other OPTION requests in their function. 
I have not found a way to distinguish a cors OPTION requests from potential business code based OPTION requests which are very rare anyway. Happy to discuss this scenario as well. 
Tell me what you think. Its a first try. Of course its tested in a real project of mine already.
=> enablePreflightReply feature added

packages/cloudwatch-metrics/__tests__/index.js, packages/cloudwatch-metrics/index.js, packages/http-cors/index.d.ts, website/docs/middlewares/cloudwatch-metrics.md
Fixes https://github.com/middyjs/middy/issues/998
[`aws-embedded-metrics` `setDimensions` function signature](https://github.com/awslabs/aws-embedded-metrics-node#metriclogger) is `Record<String, String> | Record<String, String>[]` whereas the `cloudwatch-metrics` middleware was expecting `Record<String, String>[]` and passing the dimensions args through via the spread operator, which if an empty array was passed (as per middy docs) would result in an undefined error.
This should be a backwards-compatible bug fix as the original middy `Record<String, String>[]` is a valid parameter for `setDimensions` even without the spread operator.
I've also updated the docs to reflect this change and removed the explicitly mentioned defaults as I couldn't find where in the `aws-embedded-metrics` where …
=> Fix setDimensions function arg and update docs

packages/ws-router/index.d.ts, packages/ws-router/index.test-d.ts
Shouldn't the type of each handler of the `ws-router` be `APIGatewayProxyWebsocketHandlerV2` instead of `APIGatewayProxyHandlerV2`? For example, in `APIGatewayProxyHandlerV2`, there is no `event.requestContext.connectionId` or most of the properties listed here:
https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-websocket-api-mapping-template-reference.html
This includes updating the type of the `handler` property of the `Route` type in the declaration file.
=> chore: update `ws-router` handler type

packages/event-normalizer/__tests__/index.js, packages/event-normalizer/index.js
Preventing following TypeError when there is no topic value:
```
The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
```
=> fix: kafka event handling while missing topic value

website/docs/middlewares/http-header-normalizer.md
The default is lowercase so prioritise that in the docs. Make it clear that the body parser middlewares are OK with either type of normalization.
Just a suggestion, seemed easiest as a PR. Feel free to edit or fix differently. When switching a project to middy I initially completely missed that the default behaviour was lowercase as the docs strongly imply canonical form unless you spot the default canonical false note further down the page.
=> Clarify header normalization docs

packages/http-json-body-parser/__tests__/index.js, packages/http-json-body-parser/index.js, packages/http-multipart-body-parser/__tests__/index.js, packages/http-multipart-body-parser/index.js, packages/http-urlencode-body-parser/__tests__/index.js, packages/http-urlencode-body-parser/index.js
I don't think information about what libraries a developer is using should be exposed to the public.
=> chore: remove @middy in plugin error messages

packages/core/__tests__/index.js, packages/core/index.d.ts, packages/core/index.js, packages/core/package-lock.json, packages/core/package.json, packages/http-content-encoding/__tests__/index.js, packages/http-content-encoding/index.js, packages/http-content-encoding/package-lock.json, website/docs/events/function-url.md, website/docs/intro/06-streamify-response.md, website/docs/middlewares/http-content-encoding.md
Closes #1038
Using Function URL, arm, nodejs18.x, esm
```js
import middy from '@middy/core'
export const handler = middy({ streamifyResponse: true })
.handler(() => {
return {
statusCode: ***,
headers: {
'Content-Type': 'text/plain',
'X-Custom-Header': 'Example-Custom-Header'
},
body: ***
}
})
```
=> Support streamifyResponse

packages/util/index.d.ts, packages/util/index.test-d.ts
Typescript was throwing an error when trying to work with the HttpError class (e.g. instantiating, using `instanceof`, or extending the class). I think it should declared as a class in types, since that's what it is.
=> fix(types): declare HttpError as class

packages/event-normalizer/index.js
The event normalizer middleware was doing a spread inside the reducer for dynamo db object unmarshalling. 
Replaced with mutation to reduce time complexity.
=> fix: updated dynamo unmarshall object reducer to mutate instead of spread

website/docs/integrations/lambda-powertools.md
This PR adds content to an already existing page dedicated to Powertools for AWS, a developer toolkit for serverless developer that offers custom Middy middlewares.
The idea of this page is to not replace the main Powertools docs but mainly give a high-level view of the middlewares and provide links to the main docs. 
Additionally, there's a section dedicated to best practices for working with Powertools & Middy.
I have tried to follow existing style & conventions, however if there's any change that should be made please let me know.
Below a screenshot of the rendered page for easier review:
=> docs: add content to powertools for aws page

packages/http-router/index.d.ts, packages/http-router/index.test-d.ts
This PR allows the writing of handlers that use APIGatewayProxyEventV2 / APIGatewayProxyResultV2 like the following one:
```typescript
async function postHandler(event: APIGatewayProxyEventV2, context: any): Promise<APIGatewayProxyResultV2> {
return {
statusCode: 200,
body: JSON.stringify({ message: 'POST event submitted successfully', post: event.body }),
}
}
```
I've also added a dedicated TS def test.
=> Fixes TypeScript definition for http-router

.github/workflows/release.yml
Fixes: https://github.com/middyjs/middy/issues/1074
=> fix: use lowercased aws embedded metrics import for replacement

website/docs/intro/01-intro.md
The doc for the validator middleware wraps the schema associated with the `eventSchema` in a `transpile` call.
Update `01-intro.md`'s `validator` usage to match this.
- Import `transpileSchema`
- Change variable name `eventSchema` -> `schema`
- Change parameters to `validator` middleware in example
=> docs: update `01-intro.md`'s `validator` usage

packages/appconfig/index.js, packages/dynamodb/index.js, packages/rds-signer/index.js, packages/s3/index.js, packages/secrets-manager/__tests__/index.js, packages/secrets-manager/index.js, packages/service-discovery/index.js, packages/ssm/index.js, packages/sts/index.js, packages/util/__tests__/index.js, packages/util/index.js, website/docs/middlewares/secrets-manager.md
@KillDozerX2 Can you give this a review and test? I don't personally use this service.
Adds in support for scheduled secret rotation.
Does not support manual secret rotation.
Closes: #1063
=> [secret-manager]: Add in support for secret rotation date

packages/error-logger/__tests__/index.js, packages/error-logger/index.test-d.ts, packages/http-content-negotiation/index.d.ts, packages/s3-object-response/package-lock.json
I noticed some CI issues on the 5.0 branch. This PR attempts to have a green happy CI so we can have a good starting point for the other typings changes that are expected for the final 5.0 version.
In particular this PR changes:
- missing types for `@middy/s3-object-response` (potentially due to a non up to date package-lock)
- fixing some `ts-standard` errors
- fixing some broken tests
Current status:
- Some tests are still broken apparently, more work to do!
=> Green CI for 5.0

website/docs/middlewares/http-content-encoding.md
`httpContentEncoding`, in the sample code, was being imported but was not being referenced. Updated doc to reference unused `httpContentEncoding` import and removed `httpCompressMiddleware`
=> fix: Update http-content-encoding.md

packages/util/index.d.ts
AWS SDK [v3.387.0](https://github.com/aws/aws-sdk-js-v3/releases/tag/v3.387.0) introduces the possibility to create Clients without (empty) configuration object (finally). This caused the AWS Client's middy type to be incompatible with the new SDK.
The changed type works well for both old and new SDK versions (with and without the required config parameter) and fixes failing typings tests. Although it would be best if another pair of eyes would check it with old and new SDK, just to be sure.
=> fix: type for new AWS SDK Clients with optional config parameter

packages/http-json-body-parser/index.d.ts, packages/http-json-body-parser/index.test-d.ts
=> feat(json-body-parser): allow specifying versioned APIGW events

packages/ssm/__tests__/index.js, packages/ssm/index.js
In the SSM  middleware when `fetchData` is a mix of names and paths we're seeing an issue where in some cases unless the parameters are ordered as `[...pathParams, ...namedParams]` we end up with named parameters being `undefined`
PR here for your review/discussion: it looks like the issue happens when the condition for batching causes a `continue` on all named items in a mixed list
=> SSM: fix: some mixes of named/paths results in undefined named param values

packages/http-error-handler/index.js
http-error-handler currently does not handle non http errors if `fallbackMessage` is not set.
This PR will handled all non http errors as 'Internal Server Error' even if no fallback message is configured.
I think this is a more expected behaviour of an error handler.
=> fix(http-error-handler): non http errors will always be handled 

website/src/components/Example.js, website/src/components/Example.module.css, website/src/components/HomepageSponsors.module.css
Fixes some extra padding on mobile that was introduced by adding the AWS logo (which had unexpected proportions). Also adds some other minor graphic adjustments.
=> fix(website): extra padding on mobile

website/docs/intro/06-typescript.md
=> Feat: improve TS docs, mention Middeware-first, Handler-last pattern

packages/core/index.d.ts
Each middleware can be assigned an optional name that might then handed to a plugin in the `beforeMiddleware` or `afterMiddleware` hook. This is currently not possible when using TypeScript with the default `MiddlewareObj` interface, as it does not allow the `name` property.
This PR adds an optional `name` property to the `MiddlewareObj`.
=> feat: Add name property to MiddlewareObj typings

packages/input-output-logger/__tests__/index.js, packages/input-output-logger/index.js, packages/input-output-logger/package-lock.json, packages/input-output-logger/package.json, website/docs/middlewares/input-output-logger.md
=> feat: add in support for stream reponses

packages/http-multipart-body-parser/index.js
I found that the last three parameters of the 'file' event in Busboy were not being passed correctly. The 'info' parameter was being destructured, which only pointed to the 'filename' attribute of the event.
Before the Change
After the Change
=> Add the rest of the parameters in the http-multipart-body-parser middleware

packages/http-cors/__tests__/index.js, packages/http-cors/index.js
for reference: https://github.com/middyjs/middy/pull/1133
we can call lambdas using invoke or any other way other than API gateway.
I don't think http-cors middleware should break the whole code if the event it is receiving is not a real http event, it will append to headers and that's it.
=> Do not throw error if event is not http (http-cors)

packages/core/index.d.ts, packages/core/index.test-d.ts
Middy does not support callback handlers since 1.x, the third argument is actually the timeout signal.
Fixes https://github.com/middyjs/middy/issues/1164
=> fix: remove handler callback argument

website/docs/intro/02-getting-started.md
=> fix(website): broken links in the getting started section

packages/http-header-normalizer/__tests__/index.js, packages/http-header-normalizer/index.js, packages/http-json-body-parser/__tests__/index.js
Given `canonical:  true`,
And an event containing a header that's "sanitized" (X----)
A runtime error occurs, "Cannot read property 'toUpperCase' of undefined".
**To Reproduce:**
**Unit test** 
```
test('It should not fail given a corrupted header key', async (t) => {
const handler = middy((event, context) => event)
handler.use(httpHeaderNormalizer({ canonical: true }))
const event = {
headers: {
'X----': 'foo'
}
}
const expectedHeaders = {
'X----': 'foo'
}
const originalHeaders = { ...event.headers }
const resultingEvent = await handler(event, context)
t.deepEqual(resultingEvent.headers, expectedHeaders)
t.deepEqual(resultingEvent.rawHeaders, originalHeaders)
})
```
**Thrown error:**  "Cannot read property 'toUpperCase' of undefined".
**Expected behavior:** Should simply return the raw …
=> Pkg: httpHeaderNormalizer to handle canonical sanitized headers

website/docs/integrations/lambda-powertools.md
This is a follow up PR to #1193.
In that PR a community member already updated the imports to reflect the changes in v2. This PR instead:
- updates the note at the top of the page to reflect that Powertools is compatible with v4
- adds mentions to new utilities released since last update (link only)
- updates the base url to the Powertools docs to reflect the new scheme (old url still worked thanks to redirects on our side)
For added context, we released v2 a few weeks ago but we purposefully soft launched it and waited to update docs in other repos (this being one of them) to hash out any issues.
This PR will close aws-powertools/powertools-lambda-typescript#2124
=> chore: update Powertools docs

package-lock.json, package.json, packages/core/index.d.ts, packages/core/index.test-d.ts
This should fix #1176.
I am not entirely sure this won't cause other weird typing side effects, so I'd love it if someone with some TypeScript expertise could do a thorough review.
CC @naorpeled
=> fix(types): typescript compile error

packages/http-cors/__tests__/index.js, packages/http-cors/index.js, website/docs/middlewares/http-cors.md
- Implemented support for wildcard origins
- no breaking change
When configuring the cors middleware, it is now possible to provide a wildcard origin to the origins array:
```
handler.use(
cors({
disableBeforePreflightResponse: false,
origins: ['https://example.com', 'https://*.example.com']
})
)
```
A request from a sub-domain (`https://example-subdomain.example.com`) would then result in a header that matches the subdomain:
```
'Access-Control-Allow-Origin': 'https://subdomain.example.com',
```
Hey @willfarrell , I'm proposing this change be added to the project. This change will allow user's to pass wildcard origins to the middleware. This will make it easier to administer cors headers when traffic is coming from multiple different sub-domains. 
Please let me know your thoughts! It's …
=> feat: implement wildcard support for cors origins option

packages/core/index.test-d.ts, packages/http-cors/__tests__/index.js, packages/http-multipart-body-parser/__tests__/index.js, packages/validator/__tests__/index.js
=> test(core): cover S3 middyfied handler

packages/core/index.d.ts, packages/core/index.test-d.ts
=> fix(core)!: resolve type inference issues with input handler

packages/ws-response/index.js
With commit d44e6797b2cf9dbca0b66c855217a8d0adf37200, fixing issue https://github.com/middyjs/middy/issues/1219, mutability is not required anymore on `request.response`.
=> refactor(ws-response): mutability on response

packages/core/index.d.ts, packages/core/index.test-d.ts
- This change addresses an issue where the return type of handlers was not being correctly enforced by the TypeScript compiler. As far as I could tell, the issue is caused by the `infer` keyword not working with generic types.
- Added `TResult` as a type parameter to `MiddlewareHandler` to explicitly specify the handler's return type.
- Modified the `middy` function signature to pass `TResult` to `MiddlewareHandler`.
- By explicitly specifying `TResult`, we ensure that the compiler can correctly enforce the handler's return type.
closes #1228
=> :label: ensures that handler return is properly typed

packages/http-security-headers/__tests__/index.js, packages/http-security-headers/index.d.ts, packages/http-security-headers/index.js, packages/http-security-headers/index.test-d.ts
=> feat(http-security-headers): support report only mode

packages/util/index.test-d.ts
Follow-up to https://github.com/middyjs/middy/pull/1277, this PR adds `earlyResponse: null` to the test fixture in the `utils` package. Most of the diff is automatic formatting changes.
=> chore: update test fixture

packages/core/__tests__/index.js, packages/core/index.js
Fixes #1278
@willfarrell please check my changes and comments in tests.
=> fix: support Web API ReadableStream when streamifyResponse:true

packages/core/index.d.ts, packages/core/index.test-d.ts, packages/util/index.test-d.ts
Another follow-up to https://github.com/middyjs/middy/pull/1277, I realized the `request.earlyResponse` field should be optional because the runtime code checks for it using `Object.hasOwnProperty`. Thus leaving it "empty" with a `null` value will also override the response.
So I believe this PR better aligns align the type to match the implementation. Sorry for missing this in the original PR.
=> fix: make request.earlyResponse an optional field in TypeScript type definitions

website/docs/middlewares/http-cors.md
Updates the documentation for http-cors to now that the `origin` header defaults to `null`
=> docs: update default origin for http-cors documentation

packages/http-router/index.d.ts, packages/http-router/index.test-d.ts
The `httpRouterHandler` interface is overloaded to allow the user to pass an object with the routes and a function that throws an error when the route is not found. 
This overloading was not being declared in the types, forcing the usage of `as any` when you need to pass the `notFoundResponse` method.
=> chore: add missing input type supporting notFoundResponse in http-router

packages/http-multipart-body-parser/__tests__/index.js, packages/http-multipart-body-parser/index.js
I was testing my freshly cooked lambda using Bruno and cURL. Both tools really want to add a charset to the content-type header. But the http-multipart-body-parser of Middy does not approve of that. I believe that having a charset in the content-type header is valid so I added support for it.
Based on [RFC 7231, section 3.1.1.1](https://datatracker.ietf.org/doc/html/rfc7231#section-3.1.1.1) the charset can be written in various different ways:
text/html;charset=utf-8
text/html;charset=UTF-8
Text/HTML;Charset="utf-8"
text/html; charset="utf-8"
so I made the mimePattern very lenient. The header is also passed to Busboy, I have not checked if it also uses it properly.
Let me know if it needs some additional tests or other changes!
=> fix: allow charset in multipart/formdata content-type

website/docs/middlewares/sqs-partial-batch-failure.md
---
name: Pull request
about: Pull request
title: 'docs(sqs-partial-batch-failure): clarify misleading usage instructions'
labels: ''
assignees: ''
---
The [current docs page](https://middy.js.org/docs/middlewares/sqs-partial-batch-failure/) includes examples that conflict with how the middleware actually works. Specifically:
- The first two examples show handlers returning `{ batchItemFailures }` but this return shape is not compatible with the middleware.
- The “FIFO queue” example uses `Promise.allSettled()` for parallel execution, which does not preserve processing order, which is something FIFO queues are often used for.
This PR:
- Clarifies that the middleware expects the handler to return an array of `PromiseSettledResult`s, …
=> docs(sqs-partial-batch-failure): clarify misleading usage instructions

packages/core/index.d.ts, packages/core/index.test-d.ts, packages/http-content-negotiation/index.d.ts, packages/http-header-normalizer/index.d.ts, packages/http-router/index.test.js, packages/util/type-utils.d.ts
This removes `eslint-disable` comments. Seems like those are not needed anymore, or did I misunderstood something?
**Todo List:**
- [n/a] Updated relevant types
- [n/a] Added tests (if applicable)
- [n/a] Updated relevant documentation
- [n/a] Updated relevant examples
=> chore: remove `eslint-disable` comments
